import { Request, Response } from "express";
import { resolve } from "path";
import fs from "fs";
import { minify } from "html-minifier";
const MINIFY_OPTIONS = {
  collapseBooleanAttributes: true,
  collapseInlineTagWhitespace: true,
  includeAutoGeneratedTags: false,
  keepClosingSlash: false,
  minifyJS: true,
  minifyCSS: true,
  removeAttributeQuotes: true,
};


export const HandleStatic = function (req: Request, res: Response) {
  return res.send(minify(fs.readFileSync(join('.', req.url.replace(/^/, '')), 'utf-8'), MINIFY_OPTIONS));
}
export const HandleIndex = function (req: Request, res: Response) {
  return res.sendFile(join('.', 'index.html'));
}
