import express from "express";
import * as bodyParser from "body-parser";
import { createUser, searchUsers } from "./controllers/user.controller";
import {
  createConversation,
  getAllConversations,
  addMessageToConversation,
  getConversationMessages,
} from "./controllers/conversions.controller";


import { Server } from "socket.io";
import http from "http";
import Socket from "./utils/socket";
import { minify } from "html-minifier";
import fs from 'fs';
import { createServer } from 'vite';
import { join } from "path"
const app: express.Application = express();


app.use(express.urlencoded({ extended: false }));
app.use(express.json());

const MINIFY_OPTIONS = {
  collapseBooleanAttributes: true,
  collapseInlineTagWhitespace: true,
  includeAutoGeneratedTags: false,
  keepClosingSlash: false,
  minifyJS: true,
  minifyCSS: true,
  removeAttributeQuotes: true,
};


app.get('*.html', (req: express.Request, res: express.Response) => {
  res.send(minify(fs.readFileSync(join('.', req.originalUrl), 'utf-8'), MINIFY_OPTIONS));
});
app.get("server/users/create", createUser);
app.get("/backend/users/search", searchUsers);
app.post("/conversations/create", createConversation);
app.get("*/conversations", getAllConversations);
app.post("/messages/create", addMessageToConversation);
app.get("/messages/get", getConversationMessages);
const server = http.createServer(app);
const ioServer = new Server(server);

Socket.getInstance(ioServer);
server.listen(4000);
